name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  check:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

  test:
    needs: check
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    name: Semantic Release
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build:
    needs: release
    if: needs.release.outputs.new_release_version != ''
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.release.outputs.new_release_version }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
